# print a new line at the start of the prompt
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
# [character]      # The name of the module we are configuring is "character"
# symbol = ""     # The "symbol" segment is being set to "âœ"

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 22
truncation_symbol = ""

